'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")>  _
Partial Friend NotInheritable Class Settings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()),Settings)
    
    Public Shared ReadOnly Property [Default]() As Settings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property CAhost() As String
        Get
            Return CType(Me("CAhost"),String)
        End Get
        Set
            Me("CAhost") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property CAdomain() As String
        Get
            Return CType(Me("CAdomain"),String)
        End Get
        Set
            Me("CAdomain") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property CAuser() As String
        Get
            Return CType(Me("CAuser"),String)
        End Get
        Set
            Me("CAuser") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property CApassword() As String
        Get
            Return CType(Me("CApassword"),String)
        End Get
        Set
            Me("CApassword") = value
        End Set
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files (x86)\CA\DSM\CA_FDU\PackageUpDater\mod_gsoap_utf8.dll")>  _
    Public ReadOnly Property WindowsApp1_clientauto_DSMWebServiceAPIService() As String
        Get
            Return CType(Me("WindowsApp1_clientauto_DSMWebServiceAPIService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property UseLocal() As String
        Get
            Return CType(Me("UseLocal"),String)
        End Get
        Set
            Me("UseLocal") = value
        End Set
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Http://lecri01-141em/DSM_WEBService/mod_gsoap_utf8.dll")>  _
    Public ReadOnly Property WindowsApp1_clientauto_DSMWebServiceAPIService1() As String
        Get
            Return CType(Me("WindowsApp1_clientauto_DSMWebServiceAPIService1"),String)
        End Get
    End Property
End Class
